import Products from "./models/products";

export const dummy_data: Products[] = [
  {
    id: "a1",
    name: "messi",
    image: "/images/img-1.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a2",
    name: "messi",
    image: "/images/img-2.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a3",
    name: "messi",
    image: "/images/img-3.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a4",
    name: "messi",
    image: "/images/img-4.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a5",
    name: "messi",
    image: "/images/img-5.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a6",
    name: "messi",
    image: "/images/img-6.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a7",
    name: "messi",
    image: "/images/img-7.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a8",
    name: "messi",
    image: "/images/img-8.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a9",
    name: "messi",
    image: "/images/img-9.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a10",
    name: "messi",
    image: "/images/img-10.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a11",
    name: "messi",
    image: "/images/img-11.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a12",
    name: "messi",
    image: "/images/img-12.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a13",
    name: "messi",
    image: "/images/img-13.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a14",
    name: "messi",
    image: "/images/img-14.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a15",
    name: "messi",
    image: "/images/img-15.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a16",
    name: "messi",
    image: "/images/img-16.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a17",
    name: "messi",
    image: "/images/img-17.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a18",
    name: "messi",
    image: "/images/img-18.jpeg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a19",
    name: "messi",
    image: "/images/img-19.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a20",
    name: "messi",
    image: "/images/img-20.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a21",
    name: "messi",
    image: "/images/img-21.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a22",
    name: "messi",
    image: "/images/img-22.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a23",
    name: "messi",
    image: "/images/img-23.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a24",
    name: "messi",
    image: "/images/img-24.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
  {
    id: "a25",
    name: "messi",
    image: "/images/img-25.jpg",
    color: "red",
    stars: 2,
    price: 1500,
    wheelSize: 26,
    brand: "viva",
    category: "mountain bike",
  },
];
